config/routes.rb
Rails.application.routes.draw do
  resources :models
  resources :packages
  get "pages/home"
  get "pages/adminnistration"
  resources :destinations
  get "main/index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "administration" => "main#administration"
   # Defines the root path route ("/")
   root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/model.rb
class Model < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  before_create :only_one_admin

  private
  def only_one_admin
    if User.count == 0
      self.role = 'admin'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name, :phone ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :name,  :phone ])
  end

  def only_admin
    unless user_signed_in? && current_user.role == "admin"
      redirect_to root_path, notice: "No tienes permiso para realizar esta acción"
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end

  def administration
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: %i[ show edit update destroy ]

  before_action :only_admin, only: %i[create new edit update destroy]

  # GET /models or /models.json
  def index
    @models = Model.all
  end

  # GET /models/1 or /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models or /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: "Model was successfully created." }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1 or /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: "Model was successfully updated." }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1 or /models/1.json
  def destroy
    @model.destroy!

    respond_to do |format|
      format.html { redirect_to models_path, status: :see_other, notice: "Model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def model_params
      params.require(:model).permit(:brand, :model, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Molde Prueba" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
     rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
     crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= render "shared/navbar" %>
      <%= yield %>
    </div>
    
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
  integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
  crossorigin="anonymous"></script>

  </body>
</html>

app/views/main/administration.html.erb
<h3 class="text-center">
  Página Administrativa
</h3>

<div class="text-center">
  <%= link_to "Destinos", destinations_path, class: 'btn btn-primary' %>
  <%= link_to "Paquetes Turísticos", packages_path, class: 'btn btn-primary' %>
</div>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/models/_form.html.erb
<%= form_with(model: model) do |form| %>
  <% if model.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
        <% model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/models/_model.html.erb
<div id="<%= dom_id model %>">
  <p>
    <strong>Brand:</strong>
    <%= model.brand %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= model.model %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= model.price %>
  </p>

</div>

app/views/models/edit.html.erb
<% content_for :title, "Editing model" %>

<h1>Editing model</h1>

<%= render "form", model: @model %>

<br>

<div>
  <%= link_to "Show this model", @model %> |
  <%= link_to "Back to models", models_path %>
</div>

app/views/models/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Models" %>

<h1>Models</h1>

<div id="models">
  <% @models.each do |model| %>
    <%= render model %>
    <p>
      <%= link_to "Show this model", model %>
    </p>
  <% end %>
</div>

<%= link_to "New model", new_model_path %>

app/views/models/new.html.erb
<% content_for :title, "New model" %>

<h1>New model</h1>

<%= render "form", model: @model %>

<br>

<div>
  <%= link_to "Back to models", models_path %>
</div>

app/views/models/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @model %>

<div>
  <%= link_to "Edit this model", edit_model_path(@model) %> |
  <%= link_to "Back to models", models_path %>

  <%= button_to "Destroy this model", @model, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Aplicacion</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/models">Modelos</a>
        </li>
        <% if user_signed_in? %>
          <% if current_user.role == 'admin' %>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/administration">Administrador</a>
            </li>
          <% end %>
          <li class="nav-item">
            <%= button_to 'Cerrar sesión', destroy_user_session_path, class:'nav-link', method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Iniciar sesión', new_user_session_path, class:'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to 'Registro', new_user_registration_path, class:'nav-link'%>
          </li>
      <% end %>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <div class="text-light">
          <% if user_signed_in? %>
            Hola <%=current_user.name%>
            <a data-bs-toggle="offcanvas" href="#cart">
              <i class="bi bi-cart-plus"></i>
            </a>
          <%else%>
            Visita
          <%end%>
        </div>
      </form>
    </div>
  </div>
</nav>